
	<div class="footer-main">
			


    
  <div class="content">
    <div class="menu-block-wrapper menu-block-2 menu-name-menu-footer-links parent-mlid-0 menu-level-1">
  <ul class="menu"><li class="first expanded menu-mlid-455"><span title="" class="nolink"><?php echo $this->__('About Top Ten') ?></span><ul class="menu"><li class="first leaf menu-mlid-917"><a href="<?php echo $this->__('company-overview.html') ?>" title=""><?php echo $this->__('Company Overview') ?></a></li>
<li class="leaf menu-mlid-457"><a href="<?php echo $this->__('repair.html') ?>" title=""><?php echo $this->__('Repairs') ?></a></li>
<li class="leaf menu-mlid-927"><a href="<?php echo $this->__('service-support.html') ?>" title=""><?php echo $this->__('Service and Support') ?></a></li>
<li class="last leaf menu-mlid-929"><a href="<?php echo $this->__('contact-us.html') ?>" title=""><?php echo $this->__('Contact Us') ?></a></li>
</ul></li>
<li class="expanded menu-mlid-458"><span title="" class="nolink"><?php echo $this->__('Accessories') ?></span><ul class="menu"><li class="first leaf menu-mlid-459"><a href="<?php echo Mage::getModel("catalog/category")->load(17)->getUrl() ?>" title=""><?php echo $this->__('Storage Medium') ?></a></li>
<li class="leaf menu-mlid-460"><a href="<?php echo Mage::getModel("catalog/category")->load(18)->getUrl() ?>" title=""><?php echo $this->__('Cables') ?></a></li>
<li class="leaf menu-mlid-456"><a href="<?php echo Mage::getModel("catalog/category")->load(21)->getUrl() ?>" title=""><?php echo $this->__('Spare Parts') ?></a></li>
<li class="last leaf menu-mlid-930"><a href="<?php echo Mage::getModel("catalog/category")->load(16)->getUrl() ?>" title=""><?php echo $this->__('Tape Leader') ?></a></li>
</ul></li>
<li class="expanded menu-mlid-461"><span title="" class="nolink"><?php echo $this->__('Tape Drives') ?></span><ul class="menu">
<li class="leaf menu-mlid-463"><a href="<?php echo Mage::getModel("catalog/category")->load(29)->getUrl() ?>" title=""><?php echo $this->__('LTO') ?></a></li>
<li class="leaf menu-mlid-932"><a href="<?php echo Mage::getModel("catalog/category")->load(25)->getUrl() ?>" title=""><?php echo $this->__('DAT') ?></a></li>
<li class="leaf menu-mlid-933"><a href="<?php echo Mage::getModel("catalog/category")->load(26)->getUrl() ?>" title=""><?php echo $this->__('DLT') ?></a></li>
<li class="leaf menu-mlid-934"><a href="<?php echo Mage::getModel("catalog/category")->load(27)->getUrl() ?>" title=""><?php echo $this->__('SDLT') ?></a></li>
</ul></li>
<li class="last expanded menu-mlid-464"><span title="" class="nolink"><?php echo $this->__('Manufacturer') ?></span><ul class="menu">
<li class="last leaf menu-mlid-466"><a href="<?php echo $this->__('catalogsearch/result/?q=IBM') ?>" title=""><?php echo $this->__('IBM') ?></a></li>
<li class="last leaf menu-mlid-936"><a href="<?php echo $this->__('catalogsearch/result/?q=HP') ?>" title=""><?php echo $this->__('HP') ?></a></li>
<li class="last leaf menu-mlid-937"><a href="<?php echo $this->__('catalogsearch/result/?q=Quantum') ?>" title=""><?php echo $this->__('Quantum') ?></a></li>
<li class="last leaf menu-mlid-939"><a href="<?php echo $this->__('catalogsearch/result/?q=StorageTek') ?>" title=""><?php echo $this->__('StorageTek') ?></a></li>
</ul></li>
</ul></div>
		</div>
	
		</div>
	<div class="container1">
		<div class="row">
			<div class="span12">
				<p class="copyright">
					Copyright © 2013, Top Ten. All Rights Reserved. <a href="http://www.toptenstorage.com/terms-of-use.html" onclick="_gaq.push(['_trackEvent', 'Footer', 'Terms', 'Overview']);">Terms Of Use</a><a href="http://www.toptenstorage.com/imprint.html" onclick="_gaq.push(['_trackEvent', 'Footer', 'Imprint', 'Overview']);">Imprint</a>
				</p>
							</div>

	</div>
<!--</footer>-->
