<div class="slider-wrap" style="height: 280px; overflow: hidden;">
  <div id="stripNavL0" class="stripNavL" onclick="changeFx('scrollRight')"><a id="stripNavLa" href="#">Left</a></div>
  <div id="slider-content" class="slider-wrap">
  <a href="#" title=""><img src="{{media url="home_banner.jpg"}}" alt="" width="950" height="280" /></a> 
  <a href="#" title=""><img src="{{media url="home_banner_2.jpg"}}" alt="" width="950" height="280" /></a>
  <a href="#" title=""><img src="{{media url="home_banner_3.jpg"}}" alt="" width="950" height="280" /></a>
  </div>
  <div id="stripNavR0" class="stripNavR" onclick="changeFx('fade')"><a id="stripNavRa" href="#">Right</a></div>
</div>
